// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2bmgDJXtdUsHcSgdKoDYzaTYLxv7QwBE',
    appId: '1:241019019766:web:9ead7e293e63aeff7b27d7',
    messagingSenderId: '241019019766',
    projectId: 'sonic-patti-97e4c',
    authDomain: 'sonic-patti-97e4c.firebaseapp.com',
    storageBucket: 'sonic-patti-97e4c.appspot.com',
    measurementId: 'G-EGDH2R92T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzB6JVEyw0MRkG8SwuvGC2y2dkjytdZ9I',
    appId: '1:241019019766:android:81c349546f5f44017b27d7',
    messagingSenderId: '241019019766',
    projectId: 'sonic-patti-97e4c',
    storageBucket: 'sonic-patti-97e4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPg7LF0GVao-i9LkejTAH7aMiyEJYeaZM',
    appId: '1:241019019766:ios:efd63bf45510fbe97b27d7',
    messagingSenderId: '241019019766',
    projectId: 'sonic-patti-97e4c',
    storageBucket: 'sonic-patti-97e4c.appspot.com',
    iosClientId: '241019019766-kkducqbfv2a37r17rd110lvduis6tvt5.apps.googleusercontent.com',
    iosBundleId: 'com.sprsgmx.sonicpattilive',
  );
}
